---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 13617.
--- DateTime: 2019/11/14 11:10
---

local UIBattleTopRight_C = class()

function UIBattleTopRight_C:OnInitialized(ownerWidget)
    self.ownerWidget = ownerWidget


end

function UIBattleTopRight_C:PreConstruct(IsDesignTime)

end

function UIBattleTopRight_C:Construct()
    --------------------------------------------------------------------
    --- UI Event
    --------------------------------------------------------------------
    --- 设置
    self.ownerWidget.Button_Setting.OnClicked:Add(self.ownerWidget, function(ownWidget)
        self:OnClickedButton_Setting()
    end)
end

function UIBattleTopRight_C:OnShowWindow()

end

function UIBattleTopRight_C:OnHideWindow()

end

function UIBattleTopRight_C:Destruct()

end

function UIBattleTopRight_C:OnClickedButton_Setting()
    LUIManager:ShowWindow("UIBattleSetting")
end

return UIBattleTopRight_C